# Generated by Django 4.2.23 on 2025-08-21 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_wishlistproductmodel_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistproductmodel',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.productmodel'),
        ),
    ]
