# Generated by Django 4.2.23 on 2025-08-21 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_wishlistproductmodel_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlistproductmodel',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='wishlistproductmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productmodel'),
        ),
    ]
