# Generated by Django 4.2.23 on 2025-08-22 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_productmodel_avg_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='avg_rate',
        ),
    ]
