# Generated by Django 4.2.23 on 2025-08-21 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_ordermodel_options_ordermodel_last_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='last_price',
        ),
    ]
